version: '3.4'

services:

  sqldata-test:
    image: mcr.microsoft.com/mssql/server:2017-latest

  articles-api-test:
    image: ${REGISTRY:-jimmy}/articles.api.test:${TAG:-latest}
    build:
      context: .
      dockerfile: jimmy.Articles.API/Dockerfile
      target: test
    depends_on:
      - sqldata-test
    volumes:
      - articles-test-data:-./tests-results/:/tests