version: '3.4'

# The environment variables are taken, by default, from the ".env" file defined like:
#     USER_SERVICE_USERNAME="blahblah"
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - articles-sqldata:/var/opt/mssql
    networks:
      - articles-network

  articles-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${Server=sqldata;Database=ARTICLE_DB;User Id=sa;Password=Pass@word}
      - UserServiceUsername=${USER_SERVICE_USERNAME}
      - UserServicePassword=${USER_SERVICE_PASSWORD}
      - UseXmlFormatter=${USE_XML_FORMATTER}
    networks:
      - articles-network
    ports:
      - "5102:80"
      - "9102:81"

volumes:
  articles-sqldata:
    external: false
    
networks:
  articles-network:
    name: articles-network